name: Trigger Scheduler

on:
  schedule:
    - cron: '45 0 * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP request to trigger scheduler
        run: |
          curl -X GET "https://local-geofence.onrender.com/run-scheduler" \
          -H "x-api-key: ${{ secrets.SCHEDULER_API_KEY }}"
